function sys=dc_motor_encoder_hardware_simulatedref
sys = [];
sys.child = [];
sys.NumDataTypes = 3; 
sys.DataTypes = [];
temp.EnumNames='';
temp.EnumValues = [];
temp.Name = '';
sys.DataTypes = repmat(temp,1,3);
sys.DataTypes(1).Name = 'real_T';
sys.DataTypes(2).Name = 'boolean_T';
sys.DataTypes(3).Name = 'uint8_T';
